### ISSUE TITLE
Pod Bug

### ISSUE THREAD

**Issue by xeounxzxu** [Gon-Zo/Ht_Project#4]

**Comment by xeounxzxu** [comment]
### 버그 내용
> pod install 또는 pod update 할 시 버그 발생 ... 

### 버그 콘솔

```
Debugger listening on ws://127.0.0.1:55346/d2373edf-61b9-45bb-86bb-ded9fb8a52d9
For help, see: https://nodejs.org/en/docs/inspector
Error in debuggerConnector: connect ECONNREFUSED 127.0.0.1:50527
Error: connect ECONNREFUSED 127.0.0.1:50527
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/Users/bagjeong-gyu/workspace/Ht_Project/node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js
Debugger listening on ws:/127.0.0.1:55344/cbca4436-7c5a-4973-b0dc-423863129170
For help, see: https:/nodejs.org/en/docs/inspector
Error in debuggerConnector: connect ECONNREFUSED 127.0.0.1:50527
Error: connect ECONNREFUSED 127.0.0.1:50527
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[!] Invalid `Podfile` file: 767: unexpected token at ''.

 #  from /Users/bagjeong-gyu/workspace/Ht_Project/ios/Podfile:87
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by xeounxzxu** [comment]
### 버그 해결

npm 모듈 변경 

"@react-native-community/cli-platform-ios": "3.0.0" 으로 npm 모듈 추가 시 버그 해결
